spring.application.name=dedup-service
server.port=8081

# Dedup settings
dedup.idempotent-type=bloom
dedup.store=redis
dedup.ttl-seconds=600
dedup.caffeine.max-entries=100000

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6380
spring.data.redis.username=default
spring.data.redis.password=s3cr3tPass
spring.data.redis.ssl.enabled=false
spring.data.redis.timeout=3s

# Bloom filter
dedup.bloom.name=dedup:bf:v1:
dedup.bloom.expected-insertions=5000000
dedup.bloom.fpr=0.01

# Redis Cuckoo filter
dedup.cuckoo.filter-name=dedup:cf:v1:
dedup.cuckoo.key-prefix=dedup:cf:key:

#Rules
rule.folder=rules
rule.debounce-milis=5000
rule.default-rule-type=general
rule.default-ttl=86400000

caffeine.max-size=1000
caffeine.expire-after-write-seconds=86400000

logging.level.root: INFO

spring.kafka.bootstrap-servers=localhost:19092
