services:
  redis:
    image: redis:latest
    command: [
      "redis-server",
      "--appendonly", "yes",
      "--requirepass", "s3cr3tPass",
      "--notify-keyspace-events", "Ex"   # bật expired events
    ]
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "s3cr3tPass", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
    restart: unless-stopped
  # Kafka in KRaft mode (no ZooKeeper)
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "19092:19092"
      - "19093:19093"
      - "19094:19094"
    environment:
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:19094"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:19093,CONTROLLER://0.0.0.0:19094"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092,INTERNAL://kafka:19093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_NAMES: "PLAINTEXT,INTERNAL,CONTROLLER"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_RETENTION_MS: 600000
      KAFKA_LOG_RETENTION_BYTES: 10737418240

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "18080:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:19093

  # MongoDB (no auth for local dev)
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  # Mongo UI (mongo-express)
  mongo-express:
    image: mongo-express:1.0.2-20
    container_name: mongo-express
    ports:
      - "8087:8081"
    environment:
      # No auth mode: point directly via URL
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongo
    restart: unless-stopped

    # MariaDB service
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3307:3306"  # host:container
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: "%"       # root có thể connect từ bất kỳ IP nào
      MYSQL_DATABASE: config_service
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  redis-data:
  kafka_data:
  mongo_data:
  mariadb_data: