spring.application.name=testing-service
server.port=9090

ts.dedup.mode=stub            # stub | http
ts.dedup.base-url=http://localhost:8080
ts.dedup.path=/api/dedup-check
ts.dedup.ttl-minutes=10

ts.b.mode=stub                # stub | http
ts.b.base-url=http://localhost:8080
ts.b.path=/do-transaction