spring:
  application:
    name: shipment-service

  datasource:
    url: jdbc:mariadb://mysql-hieunguyen.alwaysdata.net:3306/hieunguyen_shipment_service
    username: 426940
    password: 123123a@dedup
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:19092

server:
  port: 4953
