spring.application.name=config-service
server.port=6175

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6380
spring.data.redis.username=default
spring.data.redis.password=s3cr3tPass
spring.data.redis.ssl.enabled=false
spring.data.redis.timeout=3s

#JPA
spring.datasource.url=jdbc:mariadb://localhost:3307/config_service
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

#Rules
rule.folder=rules
rule.debounce-milis=5000
rule.default-rule-type=general
rule.default-ttl=86400000
rule.cache.threshold=3

caffeine.max-size=1000
caffeine.expire-after-write-seconds=86400000

logging.level.root: INFO
logging.level.org.springframework.data.redis.listener=DEBUG
logging.level.org.springframework.data.redis.connection=DEBUG


